[project]
name = "luna"
version = "0.1.0"
authors = [{ name = "karin0", email = "karin0@gmx.com" }]
requires-python = ">=3.14"

[project.optional-dependencies]
rich = ["rich>=14.0.0"]

[dependency-groups]
dev = ["ruff>=0.15.12"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A",
    "ANN",
    "ARG",
    "D",
    "EM",
    "ERA",
    "FAST",
    "FBT",
    "FIX",
    "PLR",
    "PTH",
    "TD",
    "COM812",

    "BLE001",
    "DTZ005",
    "DTZ006",
    "N818",
    "PLW0603",
    "PLW2901",
    "RET503",
    "RUF021",
    "RUF022",
    "RUF023",
    "SLF001",
    "TC001",
    "TC006",
    "TRY003",
    "TRY004",
    "TRY300",
    "TRY301",
    "TRY400",

    "ASYNC240",
    "B019",
    "C901",
    "E741",
    "PLC0415",
    "S101",
    "S606",
    "S607",
    "SIM105",
    "SIM115",
    "T201",
]

[tool.ruff.format]
quote-style = "preserve"

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "single"
inline-quotes = "single"
multiline-quotes = "single"

[tool.ruff.lint.isort]
lines-between-types = 1
